---
- name: Deploy and Configure Application # Ошибка 1: Добавили имя плейбука
  hosts: web
  become: true
  # vars_files: # Удалили/закомментировали здесь
  #   - vault.yml
  vars:
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_site: "datadoghq.eu"
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: app-check
            url: http://localhost:80
            timeout: 5
  
  pre_tasks:
    - name: Load encrypted variables
      ansible.builtin.include_vars: vault.yml
      no_log: true

  roles:
    - role: geerlingguy.docker
    - role: datadog.datadog

  tasks:
    - name: Install python3-docker
      ansible.builtin.apt:
        name: python3-docker
        state: present
        update_cache: true

    - name: Run test nginx container
      community.general.docker_container:
        name: app-container
        image: nginxdemos/hello:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"